# Generated by Django 3.0.3 on 2020-04-18 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20200409_1511'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Store',
        ),
    ]
