# Generated by Django 3.0.3 on 2020-03-16 03:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_id', models.CharField(max_length=50)),
                ('shop_name', models.CharField(blank=True, max_length=50, null=True)),
                ('shop_type', models.CharField(blank=True, max_length=50, null=True)),
                ('contact', models.CharField(blank=True, max_length=50, null=True)),
                ('doe', models.DateTimeField(blank=True, null=True)),
                ('gstin', models.CharField(blank=True, max_length=50, null=True)),
                ('gstcert', models.ImageField(blank=True, null=True, upload_to='emp-docs/cv/')),
                ('idproof', models.ImageField(blank=True, null=True, upload_to='emp-docs/idproof/')),
                ('address', models.TextField(blank=True, max_length=255, null=True)),
                ('location_lat', models.DecimalField(decimal_places=6, max_digits=20)),
                ('location_lon', models.DecimalField(decimal_places=6, max_digits=20)),
                ('merchant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Shops',
            },
        ),
    ]
