# Generated by Django 3.0.3 on 2020-03-13 20:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_type', models.CharField(blank=True, choices=[('FullTime', 'FullTime'), ('PartTime', 'PartTime'), ('Internship', 'Internship')], max_length=50, null=True)),
                ('contact', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.TextField(blank=True, max_length=255, null=True)),
                ('dob', models.DateTimeField(blank=True, null=True)),
                ('cv', models.ImageField(blank=True, null=True, upload_to='emp-docs/cv/')),
                ('idproof', models.ImageField(blank=True, null=True, upload_to='emp-docs/idproof/')),
                ('bankpassbook', models.ImageField(blank=True, null=True, upload_to='emp-docs/bankpassbook/')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Employees',
            },
        ),
    ]
